export const POLICE_STATION_POSITION = { x: 32, z: -10 } as const;
export const POLICE_STATION_WIDTH = 38;
export const POLICE_STATION_DEPTH = 26;
export const POLICE_STATION_FLOOR_COUNT = 3;
export const POLICE_STATION_FLOOR_HEIGHT = 4.2;
export const POLICE_STATION_FLOOR_THICKNESS = 0.25;
export const POLICE_STATION_WALL_THICKNESS = 0.3;
export const POLICE_STATION_WALL_HEIGHT = POLICE_STATION_FLOOR_HEIGHT;
export const POLICE_STATION_WINDOW_HEIGHT = 1.4;
export const POLICE_STATION_WINDOW_SILL = 1.4;
export const POLICE_STATION_WINDOW_INSET = 0.03;

export const POLICE_STATION_DOOR_WIDTH = 3.8;
export const POLICE_STATION_DOOR_HEIGHT = 3.4;
export const POLICE_STATION_DOOR_THICKNESS = 0.18;
export const POLICE_STATION_DOOR_OPEN_ANGLE = 1.4;
export const POLICE_STATION_DOOR_COLLIDER_RADIUS = 1.6;
export const POLICE_STATION_DOOR_INTERACT_RADIUS = 2.1;
export const POLICE_STATION_ENTRY_GAP = POLICE_STATION_DOOR_WIDTH + 0.6;
export const POLICE_STATION_INTERIOR_DOOR_GAP = POLICE_STATION_DOOR_WIDTH + 0.5;

export const POLICE_STATION_WALL_COLLIDER_SPACING = 1.2;
export const POLICE_STATION_WALL_COLLIDER_RADIUS = 0.55;

export const POLICE_STATION_STAIR_WIDTH = 4.5;
export const POLICE_STATION_STAIR_DEPTH = 9.6;
export const POLICE_STATION_STAIR_STEP_COUNT = 10;
export const POLICE_STATION_STAIR_CENTER_X = POLICE_STATION_WIDTH / 2 - 3.2;
export const POLICE_STATION_STAIR_CENTER_Z = 4.0;

export const POLICE_STATION_SIGN_WIDTH = 10;
export const POLICE_STATION_SIGN_HEIGHT = 2.4;

export const POLICE_STATION_WALL_COLOR = 0xd8d2c5;
export const POLICE_STATION_TRIM_COLOR = 0x7b6a51;
export const POLICE_STATION_FLOOR_COLOR = 0x8a7f70;
export const POLICE_STATION_GLASS_COLOR = 0xaed7ff;
export const POLICE_STATION_METAL_COLOR = 0x7c8892;
export const POLICE_STATION_LIGHT_COLOR = 0xfff0d8;
